config/routes.rb
Trello::Application.routes.draw do
  get "teams/index"
  get "board/index"
  get "users/index"
  devise_for :users

  resources :users do
    resources :boards
    resources :teams
  end
  root 'users#front_page'

end

app/models/board.rb
class Board < ActiveRecord::Base
	has_many :board_users
	has_many :users, through: :board_users
	has_many :board_teams
	has_many :teams, through: :board_teams
end

app/models/board_team.rb
class BoardTeam < ActiveRecord::Base
  belongs_to :board
  belongs_to :team
end

app/models/board_user.rb
class BoardUser < ActiveRecord::Base
  belongs_to :board
  belongs_to :user
end

app/models/team.rb
class Team < ActiveRecord::Base
  has_many :team_users
  has_many :users, through: :team_users
  has_many :board_teams
  has_many :boards, through: :board_teams
end

app/models/team_user.rb
class TeamUser < ActiveRecord::Base
  belongs_to :team
  belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  # assosiations
  has_many :board_users
  has_many :board, through: :board_users
  has_many :team_users
  has_many :teams, through: :team_users
  # callbacks
  after_create :send_welcome_mail



  # methods

  def send_welcome_mail
  	@user = self
  	UserMailer.welcome_email(@user).deliver
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_action :configure_permitted_parameters, if: :devise_controller?

  def configure_permitted_parameters
  # Permit the `subscribe_newsletter` parameter along with the other
  # sign up parameters.
  devise_parameter_sanitizer.for(:sign_up) << :name
  devise_parameter_sanitizer.for(:sign_up) << :phone_no
  devise_parameter_sanitizer.for(:sign_up) << :nic_name
  # devise_parameter_sanitizer.permit(:sign_up, keys: [:name,:phone_no,:nic_name])
  end
end

app/controllers/boards_controller.rb
class BoardsController < ApplicationController
  def index

  end

  def new
  	@board = Board.new
  	@teams = Team.all
  	# @board_team = BoardTeam.new(teams: Team.all)
  end

  def create
    @board = Board.new(board_params)
    @board_team = @board.board_teams.new(team_id: params[:team_id])
    # @board.team_id = params[:team_id]
    # @board_team = Team.find(params[:team_id])
    if @board.save && @board_team.save
      # @board_team.boards << @board
      redirect_to user_board_path(current_user, @board)
    else
      render 'new'
    end
  end

  def show
    @board = Board.find(params[:id])
    @board_teams = @board.teams
    # @board_team = Team.find(params[:team_id])
  end

  def edit
    @board = Board.find(params[:id])
    @teams = Team.all
  end

  def update
    @board = Board.find(params[:id])
    @team = Team.find(params[:team_id])
    if @board.update(board_params)
      if @team.present?
        @board.update(team_id: @team.id)
      end
      redirect_to user_board_path(current_user, @board)
    else
      render 'edit'
    end
  end

  def destroy
    @board = Board.find(params[:id])
    @board.destroy
    redirect_to users_path
  end

  private
  def board_params
  	params.require(:board).permit(:title)
  end
end

app/controllers/teams_controller.rb
class TeamsController < ApplicationController

  def index
    @teams = Team.all
  end
  
  def show
    @team = Team.find(params[:id])
  end

  def new
    @team = Team.new
  end

  def edit
    @team = Team.find(params[:id])
  end

  def create
    @team = Team.new(team_params)
    if @team.save
      redirect_to user_team_path(current_user, @team)
    else
      render 'new'
    end
  end

  def update
    @team = Team.find(params[:id])
    if @team.update(team_params)
      redirect_to user_team_path(current_user, @team)
    else
      render 'edit'
    end
  end

  def destroy
    @team = Team.find(params[:id])
    @team.destroy
    redirect_to users_path
  end


  private
  def team_params
  	params.require(:team).permit(:name, :description)
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  
  def index
  	@users = User.all
    @teams = Team.all
    # binding.pry
    # @boards = current_user.boards
  end

  def show
  	@user = User.find(params[:id]) if params[:id]
  end

  def edit
  	@user = User.find(params[:id]) if params[:id]
  end

  def update
  	@user = User.find(params[:id])
  	respond_to do |format|
	    if @user.update(user_params)
	      format.html { redirect_to @user, notice: 'User was successfully updated.' }
	    else
	      format.html { render action: 'edit' }
	    end
  	end
  end

  def front_page
  	# if current_user.present?
  	# 	redirect_to users_path
  	# end
  end

  # def destroy
  #   redirect_to root_path    
  # end

  private

  def user_params
  	params.require(:user).permit(:name, :phone_no, :nic_name)
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/board_helper.rb
module BoardHelper
end

app/helpers/teams_helper.rb
module TeamsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/boards/edit.html.erb
<section id = "form">
  <div class= "container">
    <div class="col-sm-8 col-sm-offset-2 new_board">
      <div class="panel panel-default">
        <div class="panel-heading">
          <h2>Edit Team</h2>
        </div>
        <div class="panel-body">
          <%= form_for :board, url: user_board_path(current_user, @board),  method: :patch do |f| %>
              <div class="form-group">
                <%= f.label :title, class: "col-sm-4 control-label", style: "text-align: center" %>
                <div class="col-sm-6">
                  <%= f.text_field :title, class: "form-control", autofocus: true %>
                </div><br />
              </div><br />
              <div class="form-group">
                <%= f.label :team, class: "col-sm-4 control-label", style: "text-align: center" %>
                <div class="col-sm-6">
                  <%=select_tag 'team_id', options_for_select(@teams.collect{ |u| [u.name, u.id] })%>
                  <%#= select_tag :team, @teams.collect{ |u| [u.name, u.id]} %>
                </div><br />
              </div><br />
              <div class="form-group">
                <div class="col-sm-offset-2 col-sm-4">
                  <%= f.submit "Update",class: "btn btn-default submit" %>
                </div>
              </div>
          <% end %><br /><br />
        </div>
      </div>
    </div>
  </div>
</section>

app/views/boards/index.html.erb
<h1>Board#index</h1>
<p>Find me in app/views/board/index.html.erb</p>

app/views/boards/new.html.erb
<section id = "form">
  <div class= "container">
    <div class="col-sm-8 col-sm-offset-2 new_board">
      <div class="panel panel-default">
        <div class="panel-heading">
          <h2 style="text-align: center;">Create Board</h2>
        </div>
        <div class="panel-body">
          <%= form_for :board, url: user_boards_path do |f| %>
              <div class="form-group">
                <%= f.label :title, class: "col-sm-4 control-label", style: "text-align: center" %>
                <div class="col-sm-6">
                  <%= f.text_field :title, class: "form-control", autofocus: true %>
                </div><br />
              </div><br />
              <div class="form-group">
                <%= f.label :team, class: "col-sm-4 control-label", style: "text-align: center" %>
                <div class="col-sm-6">
                  <%=select_tag 'team', options_for_select(@teams.collect{ |u| [u.name, u.id] })%>
                  <%#= select_tag :team, @teams.collect{ |u| [u.name, u.id]} %>
                </div><br />
              </div><br />
              <div class="form-group">
                <div class="col-sm-offset-2 col-sm-4">
                  <%= f.submit "Create",class: "btn btn-default submit" %>
                </div>
              </div>
          <% end %><br /><br />
        </div>
      </div>
    </div>
  </div>
</section>

          
          

app/views/boards/show.html.erb
<section id = "form">
  <div class= "container">
    <div class="col-sm-8 col-sm-offset-2 new_board">
      <div class="panel panel-default">
        <div class="panel-heading">
          <h2 style="text-align: center;"><%= "#{current_user.name} created board" %></h2>
        </div>
        <div class="panel-body">
          <div class="col-sm-6 col-sm-offset-4">
						<p>
						  <b>Title:</b>
						  <%= @board.title %>
						</p>
						<p>
						  <b>Team:</b>
						  <%# @board_teams.each do |board_team| %>
						  	<%= @team.name %>
						  <%# end %>
						</p>
					<%= link_to 'Edit', edit_user_board_path(current_user, @board) %>
					<%= link_to 'Back', users_path %>
					</div>
				</div>
      </div>
    </div>
  </div>
</section>

app/views/layouts/_footer.html.erb
<footer>
	<div class="sync-img"> 
		<div class="col-sm-4 col-sm-offset-3" style="order:1; -webkit:order: 1; margin-top: 130px;"> 
			<h2>Always In Sync</h2> 
			<p>No matter where you are, Trello stays in sync across all of your devices. Collaborate with your team anywhere, from sitting on the bus to sitting on the beach.</p>
		</div>
	</div>
</footer>

app/views/layouts/_header.html.erb
<header id="header"><!--header-->
  <div class="header-middle" style="background-color: #00adff"><!--header-middle-->
    <div class="container">
      <div class="row">
        <div class="col-sm-4">
          <div class="logo pull-left">
            <%= link_to image_tag("/assets/logo.png", size: "80x80", alt: "Trello"), root_path %>
          </div>
        </div>
        <div class="col-sm-8">
          <div class="shop-menu pull-right">
            <ul class="nav navbar-nav">
              <li class= "button" style="margin-top: 15px">
              <% if user_signed_in? %>
                <%= link_to "#{current_user.name}.present?" ? "Login with: #{current_user.name}" : "Login with: #{current_user.email}", edit_user_registration_path, class: "link popup"  %>
                  <!-- <div id="popover_content_wrapper" style="display: none">
                    <ul> -->
                      <!-- <li><%#= link_to 'Edit profile', edit_user_registration_path %></li> -->
                      <li style="margin-top: 15px"><%= link_to "Logout", destroy_user_session_path, method: :delete, class: "link" %></li>
                   <!--  </ul>
                  </div> -->
                </li>
              <%#= link_to 'Edit profile', edit_user_registration_path, :class => 'navbar-link' %>
              <%#= link_to 'Addresses', addresses_path, :class => 'navbar-link' %>
              <% else %>
                <li style="margin-top: 15px"><%= link_to "Sign up", new_user_registration_path, class: "link"  %></li>
                <li style="margin-top: 15px"><%= link_to 'Login'.html_safe, new_user_session_path, class: "link"  %></li>
              <% end %>
            </ul>
          </div>
        </div>
      </div>
    </div>
  </div><!--/header-middle-->
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Trello</title>
  <%= stylesheet_link_tag    "/assets/application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "/assets/jquery-2.2.3.min.js", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "/assets/application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>
	<%= render 'layouts/header.html' %>
<%= yield %>
	<%= render 'layouts/footer.html' %>
</body>
</html>

app/views/users/edit.html.erb
<section id = "form">
  <div class= "container">
    <div class="panel panel-default">
      <div class="panel-heading">
        <h2>Edit User</h2>
      </div>
      <div class="panel-body">
        <%= form_for(@user) do |f| %>
            <div class="form-group">
              <%= f.label :user_name, class: "col-sm-2 control-label" %>
              <div class="col-sm-4">
                <%= f.text_field :name, class: "form-control", autofocus: true %>
              </div><br />
            </div><br />
            <div class="form-group">
              <%= f.label :phone_no, class: "col-sm-2 control-label" %>
              <div class="col-sm-4">
                <%= f.text_field :phone_no, class: "form-control", autofocus: true %>
              </div><br />
            </div><br />
            <div class="form-group">
              <%= f.label :nic_name, class: "col-sm-2 control-label" %>
              <div class="col-sm-4">
                <%= f.text_field :nic_name, class: "form-control", autofocus: true %>
              </div><br />
            </div><br />
            <div class="form-group">
              <%= f.label :email, class: "col-sm-2 control-label" %>
              <div class="col-sm-4">
                <%= f.email_field :email, class: "form-control", autofocus: true %>
              </div><br />
            </div><br />
            <div class="form-group">
              <div class="col-sm-offset-2 col-sm-4">
                <%= f.submit "Update",class: "btn btn-default submit" %>
              </div>
            </div>
        <% end %><br /><br />
      </div>
    </div>
  </div>
</section>

          
          

app/views/users/front_page.html.erb
<section class="trello">
	<div class="row1">
		<div class="col-sm-4 col-sm-offset-3 box"> 
			<h1>Trello lets you work more collaboratively and get more done.</h1><br />
			<p>Trello’s boards, lists, and cards enable you to organize and prioritize your projects in a fun, flexible and rewarding way. </p><br />
			<%= link_to 'Sign Up', new_user_registration_path, class: "button box1" %>
		</div>   
		<div class="box2 col-sm-4"> 
			<p class="small">Already use Trello? 
				<%= link_to 'Login', new_user_session_path, class: "button" %>
			</p> 
		</div>  
	</div><br>
	<div class="row1">
		<div class="col-sm-4 col-sm-offset-3 box"> 
			<h1>Trello lets you work more collaboratively and get more done.</h1><br />
			<p>Trello’s boards, lists, and cards enable you to organize and prioritize your projects in a fun, flexible and rewarding way. </p><br />
			<%= link_to 'Create a Team', new_user_team_path(current_user), class: "button box1" %>
		</div>   
		<div class="box2 col-sm-4"> 
			<p class="small">Already use Trello? 
				<%= link_to 'Create a Board', new_user_board_path(current_user), class: "button" %>
			</p> 
		</div>  
	</div>
</section>

app/views/users/index.html.erb
<section class="trello">
	<% @teams.each do |team|%>
		<div class="container col-sm-4" style="margin-top: 150px;">
			<div class="set-team" style="margin-bottom: 40px;">
				<ul style="list-style-type: none;">
					<li><p class="text"><%= team.name %></p></li>
					<li><p class="text"><%= link_to "Members", "/users" %></p></li>
					<li><p class="text"><%= link_to "Settings", "/#"%></p></li>
				</ul>
			</div>
			<div class="panel panel-default" style="height: 150px;background-color: #00ffd0;">
				<%# @users.each do |user|%>
					<%# if current_user.id != user.id %>
					<div class= "row">
						<div class="col-sm-8" style="padding: 65px; margin-left: 4px;">
							<%= link_to "Create a new board", new_user_board_path(current_user), class: "text" %><br />
						</div><br />
					</div>
					<%# end %>
				<%# end %>
			</div>
		</div>
	<% end %>
	<div class="col-sm-6">
		<%= link_to "Create a new team", new_user_team_path(current_user), class: "text" %><br />
	</div>
</section>

app/views/users/show.html.erb
<p>
  <b>Username:</b>
  <%= @user.name %>
</p>
<p>
  <b>Email:</b>
  <%= @user.email %>
</p>
<p>
  <b>Telephone:</b>
  <%= @user.phone_no %>
</p>
<p>
  <b>Nic Name:</b>
  <%= @user.nic_name %>
</p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>